export const FETCH_STOCKS_SUCCESS = 'FETCH:STOCKS:SUCCESS';
export const FETCH_VERSION_SUCCESS = 'FETCH:VERSION:SUCCESS';

export const ARRANGE_STOCKS_SUCCESS = 'ARRANGE:STOCKS:SUCCESS';

export const USER_LOGIN_SUCCESS = 'USER:LOGIN:SUCCESS';
export const USER_LOGIN_FAIL = 'USER:LOGIN:FAIL';


export const REFRESH_TOKEN_SUCCESS = 'REFRESH:TOKEN:SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH:TOKEN:FAIL';
